### ISSUE TITLE
Wrong Mill Restore for Premium Cards

### ISSUE THREAD

**Issue by Daviex** [GwentAPI/gwentapi#27]
Hello.

Using the API, I found out that the Premium Mill value is the same of the Standard in all the cards.
I wanted just to issue this 👍

**Comment by Tri125** [comment]
Can you provide an example and write what the correct value should be so I can look this up?

**Comment by Daviex** [comment]
Yeah, sure.

Over your API, Adrenaline Rush says it cost both 10 forma standard and premium.

From GwentDB, it says it cost 10/50:
http://www.gwentdb.com/cards/50037-adrenaline-rush

Maybe is wrong GwentDB, but the thing that is a premium card made me think about this ^^'

**Comment by Tri125** [comment]
Thank you.
After doing some minor verification in-game and discussing it with some people we came to the conclusion that GwentDB is in the wrong. This [thread](http://www.gwentdb.com/forums/gwentdb/site-feedback-support/658-mill-cost-wrong-on-database) on their forum seems to support this. Most, if not all, premium cards have the same mill *scrap* value as their normal counterpart.

This wouldn't be the first time that GwentDB have incorrect data. I would personally recommend http://gwentify.com/cards/ for people who wants to look up cards or build decks in a visually pleasing way.

**Comment by Daviex** [comment]
Ok thank you for the response, I was thinking it was alright because of the value of a premium card, and seem legit to me that a Premium would give me more Mill than Standard eheh.

Anyway, thanks again for you speed :)
