### ISSUE TITLE
Some card images are out of date

### ISSUE THREAD

**Issue by cg5-** [GwentAPI/gwentapi#30]
For example, [here is the image for Wild Hunt Hound](https://api.gwentapi.com/media/wild-hunt-hound-thumbnail.png). It still has 5 strength, instead of 4.

**Comment by Tri125** [comment]
I'll push the updated one tomorrow.

**Comment by Tri125** [comment]
Sorry for the delay. The most recent artworks that I got should be part of the API now. Expect delay before seeing the updated version as the CDN edge cache needs to expire. If after 24h there is an artwork that is still incorrect (make sure to clear your browser cache first), feel free to contact me.
