### ISSUE TITLE
New patch is out with lots of cards change

### ISSUE THREAD

**Issue by zhouzi** [GwentAPI/gwentapi#34]
Hooray, the new patch is out 🎉 

Lots of cards have changed and there are some new ones too.

**Comment by Soreine** [comment]
Hello @Tri125
I think the implicit question here is when will the cards will be updated and what should we do to help you with that.
We are excited to have our Chrome extension cover the new patch, hence the casual tone of @Zhouzi :)

**Comment by zhouzi** [comment]
The API seems to be up to date but the cards' images are missing (throwing a 404). Reading https://github.com/GwentAPI/gwentapi/issues/23#issuecomment-314112361, I feel like the amount of work required to maintain the API is pretty high. I hope we can help!

Is the data still pulled from crawling gwentify through [arachas](https://github.com/GwentAPI/arachas)? I am looking at the code right now and can give a hand to maintain it.

**Comment by Tri125** [comment]
Sorry, I should have commented before closing the issue, that was pretty rude.

Please check [GwentAPI twitter account for public announcement](https://twitter.com/GwentAPI).

Artworks are never going to be on the same day as a data update. I have to patiently wait for a busy CD RED employee to send me the updated artworks OR wait for other generous community devs to upload the new artworks after a busy CD RED employee sent them the artworks. When I finally get hold on them it might or might not be when I'm also available to work on the API.

**Comment by Tri125** [comment]
Also, you can keep an eye on [/u/gwentAPI](https://www.reddit.com/user/gwentAPI) for bigger announcement.

Artworks have now been updated. :+1:

**Comment by zhouzi** [comment]
Thanks @Tri125 💪  I'll make sure to follow the Twitter and Reddit account. I went through the READMEs but I'm unsure about the overall process you have to go through to update the API. From my understanding, it looks like:

1. Crawl gwentify with arachas for cards data
2. Upload the images (sent by a CD RED employee)
3. Feed the mongo database
4. Deploy

Am I right? Arachas' README says it's deprecated so if not crawling gwentify, how are you getting the data?

**Comment by Tri125** [comment]
Well, this one isn't outdated :P https://github.com/GwentAPI/gwentapi/blob/master/DATABASE_INSTRUCTIONS.md
Not distributing json for legal reason.

**Comment by zhouzi** [comment]
Hehe thanks! Actually, it says:

> Obtain a copy of the card data in json

How do you obtain it? Is the program outputting it?

**Comment by Tri125** [comment]
Ping me up on reddit. This won't be discussed here.
