### ISSUE TITLE
Card and variation id Swapped in variation href

### ISSUE THREAD

**Issue by cr0wst** [GwentAPI/gwentapi#7]
Querying a card and a variation is populating the href for the variation incorrectly.  The card id and variation id are swapped.  

Example:
Card:
https://api.gwentapi.com/v0/cards/Xi1HAfdAROepSvrGFPADTQ

First variation href: https://api.gwentapi.com/v0/cards/lJtg9njfTAqfPUUr3nJoJw/variations/Xi1HAfdAROepSvrGFPADTQ

This is showing as /cards/{variationID}/variations/{cardID}.

It looks like at some point VariationURL's parameters were switched on [line 43](https://github.com/GwentAPI/gwentapi/blame/428bac414bc8646f9a4a03f673a8ef64e05b517e/dataLayer/factory/FactoryVariation.go#L43) of FactoryVariation via cd8d06dbc34bd5526cf3ef9a181f6fcc84e063f6.  However, [line 64](https://github.com/GwentAPI/gwentapi/blame/428bac414bc8646f9a4a03f673a8ef64e05b517e/dataLayer/factory/FactoryVariation.go#L64) still has the old parameter order.

**Comment by Tri125** [comment]
Thank you for the report.
This is fixed in 9a2cd1b3bb1b045a8bab8220bdc98d8f66817a07 and should be live.

**Comment by cr0wst** [comment]
Looks good now! 👍
